export function useUtils() {
const longNameFormatter = (name) =>{
  if(name.length > 23 ){
    return name.substr(0,23)+".."
  }
  return name
}
const artistListFormatter = (input) =>{
  let artists = [...input]
  if(artists.length == 1){
    return longNameFormatter(artists[0])
  } 
  let string = ""
  artists.reverse()


  artists.forEach(e => {
        if(string == ""){
      string = artists[0]
    }else{
      string += ", "+e
    } 
  });
  return longNameFormatter(string.trim())
}

const getNationalityByCode = (input) =>{
  let list = nationalityList()
  const match = list.find(e => e.code == input)
  return match ? match.name : "Nem ismert"
}

const nationalityList = () =>{
  return [
  { code: null, name: 'Nem ismert' },
  { code: 'afg', name: 'Afganisztán' },
  { code: 'alb', name: 'Albánia' },
  { code: 'dza', name: 'Algéria' },
  { code: 'and', name: 'Andorra' },
  { code: 'ago', name: 'Angola' },
  { code: 'atg', name: 'Antigua és Barbuda' },
  { code: 'arg', name: 'Argentína' },
  { code: 'arm', name: 'Örményország' },
  { code: 'aus', name: 'Ausztrália' },
  { code: 'aut', name: 'Ausztria' },
  { code: 'aze', name: 'Azerbajdzsán' },
  { code: 'bhs', name: 'Bahama-szigetek' },
  { code: 'bhr', name: 'Bahrein' },
  { code: 'bgd', name: 'Banglades' },
  { code: 'brb', name: 'Barbados' },
  { code: 'blr', name: 'Fehéroroszország' },
  { code: 'bel', name: 'Belgium' },
  { code: 'blz', name: 'Belize' },
  { code: 'ben', name: 'Benin' },
  { code: 'btn', name: 'Bhután' },
  { code: 'bol', name: 'Bolívia' },
  { code: 'bih', name: 'Bosznia-Hercegovina' },
  { code: 'bwa', name: 'Botswana' },
  { code: 'bra', name: 'Brazília' },
  { code: 'brn', name: 'Brunei' },
  { code: 'bgr', name: 'Bulgária' },
  { code: 'bfa', name: 'Burkina Faso' },
  { code: 'bdi', name: 'Burundi' },
  { code: 'cpv', name: 'Zöld-foki Köztársaság' },
  { code: 'khm', name: 'Kambodzsa' },
  { code: 'cmr', name: 'Kamerun' },
  { code: 'can', name: 'Kanada' },
  { code: 'caf', name: 'Közép-afrikai Köztársaság' },
  { code: 'tcd', name: 'Csád' },
  { code: 'chl', name: 'Chile' },
  { code: 'chn', name: 'Kína' },
  { code: 'col', name: 'Kolumbia' },
  { code: 'com', name: 'Comore-szigetek' },
  { code: 'cod', name: 'Kongó (DRK)' },
  { code: 'cog', name: 'Kongó (Köztársaság)' },
  { code: 'cri', name: 'Costa Rica' },
  { code: 'hrv', name: 'Horvátország' },
  { code: 'cub', name: 'Kuba' },
  { code: 'cyp', name: 'Ciprus' },
  { code: 'cze', name: 'Csehország' },
  { code: 'dnk', name: 'Dánia' },
  { code: 'dji', name: 'Dzsibuti' },
  { code: 'dom', name: 'Dominikai Köztársaság' },
  { code: 'ecu', name: 'Ecuador' },
  { code: 'egy', name: 'Egyiptom' },
  { code: 'slv', name: 'Salvador' },
  { code: 'gnq', name: 'Egyenlítői-Guinea' },
  { code: 'eri', name: 'Eritrea' },
  { code: 'est', name: 'Észtország' },
  { code: 'swz', name: 'Szváziföld' },
  { code: 'eth', name: 'Etiópia' },
  { code: 'fji', name: 'Fidzsi' },
  { code: 'fin', name: 'Finnország' },
  { code: 'fra', name: 'Franciaország' },
  { code: 'gab', name: 'Gabon' },
  { code: 'gmb', name: 'Gambia' },
  { code: 'geo', name: 'Grúzia' },
  { code: 'deu', name: 'Németország' },
  { code: 'gha', name: 'Ghána' },
  { code: 'grc', name: 'Görögország' },
  { code: 'grd', name: 'Grenada' },
  { code: 'gtm', name: 'Guatemala' },
  { code: 'gin', name: 'Guinea' },
  { code: 'gnb', name: 'Bissau-Guinea' },
  { code: 'guy', name: 'Guyana' },
  { code: 'hti', name: 'Haiti' },
  { code: 'hnd', name: 'Honduras' },
  { code: 'hun', name: 'Magyarország' },
  { code: 'isl', name: 'Izland' },
  { code: 'ind', name: 'India' },
  { code: 'idn', name: 'Indonézia' },
  { code: 'irn', name: 'Irán' },
  { code: 'irq', name: 'Irak' },
  { code: 'irl', name: 'Írország' },
  { code: 'isr', name: 'Izrael' },
  { code: 'ita', name: 'Olaszország' },
  { code: 'jam', name: 'Jamaica' },
  { code: 'jpn', name: 'Japán' },
  { code: 'jor', name: 'Jordánia' },
  { code: 'kaz', name: 'Kazahsztán' },
  { code: 'ken', name: 'Kenya' },
  { code: 'kir', name: 'Kiribati' },
  { code: 'prk', name: 'Észak-Korea' },
  { code: 'kor', name: 'Dél-Korea' },
  { code: 'kwt', name: 'Kuvait' },
  { code: 'kgz', name: 'Kirgizisztán' },
  { code: 'lao', name: 'Laosz' },
  { code: 'lva', name: 'Lettország' },
  { code: 'lbn', name: 'Libanon' },
  { code: 'lso', name: 'Lesotho' },
  { code: 'lbr', name: 'Libéria' },
  { code: 'lby', name: 'Líbia' },
  { code: 'lie', name: 'Liechtenstein' },
  { code: 'ltu', name: 'Litvánia' },
  { code: 'lux', name: 'Luxemburg' },
  { code: 'mdg', name: 'Madagaszkár' },
  { code: 'mwi', name: 'Malawi' },
  { code: 'mys', name: 'Malajzia' },
  { code: 'mdv', name: 'Maldív-szigetek' },
  { code: 'mli', name: 'Mali' },
  { code: 'mlt', name: 'Málta' },
  { code: 'mhl', name: 'Marshall-szigetek' },
  { code: 'mrt', name: 'Mauritánia' },
  { code: 'mus', name: 'Mauritius' },
  { code: 'mex', name: 'Mexikó' },
  { code: 'fsm', name: 'Mikronézia' },
  { code: 'mda', name: 'Moldova' },
  { code: 'mco', name: 'Monaco' },
  { code: 'mng', name: 'Mongólia' },
  { code: 'mne', name: 'Montenegró' },
  { code: 'mar', name: 'Marokkó' },
  { code: 'moz', name: 'Mozambik' },
  { code: 'mmr', name: 'Mianmar' },
  { code: 'nam', name: 'Namíbia' },
  { code: 'nru', name: 'Nauru' },
  { code: 'npl', name: 'Nepál' },
  { code: 'nld', name: 'Hollandia' },
  { code: 'nzl', name: 'Új-Zéland' },
  { code: 'nic', name: 'Nicaragua' },
  { code: 'ner', name: 'Niger' },
  { code: 'nga', name: 'Nigéria' },
  { code: 'mkd', name: 'Észak-Macedónia' },
  { code: 'nor', name: 'Norvégia' },
  { code: 'omn', name: 'Omán' },
  { code: 'pak', name: 'Pakisztán' },
  { code: 'plw', name: 'Palau' },
  { code: 'pan', name: 'Panama' },
  { code: 'png', name: 'Pápua Új-Guinea' },
  { code: 'pry', name: 'Paraguay' },
  { code: 'per', name: 'Peru' },
  { code: 'phl', name: 'Fülöp-szigetek' },
  { code: 'pol', name: 'Lengyelország' },
  { code: 'prt', name: 'Portugália' },
  { code: 'qat', name: 'Katar' },
  { code: 'rou', name: 'Románia' },
  { code: 'rus', name: 'Oroszország' },
  { code: 'rwa', name: 'Ruanda' },
  { code: 'kna', name: 'Saint Kitts és Nevis' },
  { code: 'lca', name: 'Saint Lucia' },
  { code: 'vct', name: 'Saint Vincent és a Grenadine-szigetek' },
  { code: 'wsm', name: 'Szamoa' },
  { code: 'smr', name: 'San Marino' },
  { code: 'stp', name: 'São Tomé és Príncipe' },
  { code: 'sau', name: 'Szaúd-Arábia' },
  { code: 'sen', name: 'Szenegál' },
  { code: 'srb', name: 'Szerbia' },
  { code: 'syc', name: 'Seychelle-szigetek' },
  { code: 'sle', name: 'Sierra Leone' },
  { code: 'sgp', name: 'Szingapúr' },
  { code: 'svk', name: 'Szlovákia' },
  { code: 'svn', name: 'Szlovénia' },
  { code: 'slb', name: 'Salamon-szigetek' },
  { code: 'som', name: 'Szomália' },
  { code: 'zaf', name: 'Dél-Afrika' },
  { code: 'ssd', name: 'Dél-Szudán' },
  { code: 'esp', name: 'Spanyolország' },
  { code: 'lka', name: 'Srí Lanka' },
  { code: 'sdn', name: 'Szudán' },
  { code: 'sur', name: 'Suriname' },
  { code: 'swe', name: 'Svédország' },
  { code: 'che', name: 'Svájc' },
  { code: 'syr', name: 'Szíria' },
  { code: 'twn', name: 'Tajvan' },
  { code: 'tjk', name: 'Tádzsikisztán' },
  { code: 'tza', name: 'Tanzánia' },
  { code: 'tha', name: 'Thaiföld' },
  { code: 'tls', name: 'Kelet-Timor' },
  { code: 'tgo', name: 'Togo' },
  { code: 'ton', name: 'Tonga' },
  { code: 'tto', name: 'Trinidad és Tobago' },
  { code: 'tun', name: 'Tunézia' },
  { code: 'tur', name: 'Törökország' },
  { code: 'tkm', name: 'Türkmenisztán' },
  { code: 'tuv', name: 'Tuvalu' },
  { code: 'uga', name: 'Uganda' },
  { code: 'ukr', name: 'Ukrajna' },
  { code: 'are', name: 'Egyesült Arab Emírségek' },
  { code: 'gbr', name: 'Egyesült Királyság' },
  { code: 'usa', name: 'Egyesült Államok' },
  { code: 'ury', name: 'Uruguay' },
  { code: 'uzb', name: 'Üzbegisztán' },
  { code: 'vut', name: 'Vanuatu' },
  { code: 'ven', name: 'Venezuela' },
  { code: 'vnm', name: 'Vietnám' },
  { code: 'yem', name: 'Jemen' },
  { code: 'zmb', name: 'Zambia' },
  { code: 'zwe', name: 'Zimbabwe' }
]
}

  return {
    longNameFormatter,
    artistListFormatter,
    nationalityList,
    getNationalityByCode,
  }
}